// all this stuff is client side

lvl1Data = [
  "bonjour cryptique",
  "coucou hasardeux",
  "hi! hypocrite",
  "shalom audacieux",
  "habile buongiorno",
  "à bientot sceptique",
  "kenavo sardonique",
  "sayonara risqué",
  "adieu impatient",
  "ciao apathique",
  "arrivederci zélé",
  "take care exagéré",
  "tot ziens discret",
  "gruezi décomplexé",
  "tschuss implacable",
];

lvl2Data = [
  "ça va ?",
  "curieux.",
  "oui et vous",
  "conventionnel",
  "ça va aussi",
  "automatique",
  "et alors",
  "annonciateur,",
  "que pensez-vous",
  "indiscret,",
  "de la vitesse",
  "à laquelle",
  "je tape ces mots",
  "présomptueux.",
  "?",
  "pas mal",
  "poli",
  "mais en",
  "meme temps",
  "acrimonieux",
  "c'est pas",
  "des mots",
  "très compliqués",
  "prémonitoire.",
];

lvl3Data = [
  "la touche a",
  "la touche b",
  "la touche c",
  "la touche d",
  "la touche e",
  "la touche f",
  "la touche g",
  "la touche h",
  "la touche i",
  "la touche",
  "la touche @",
  "la touche &",
  "la touche é",
  `la touche "`,
  "la touche '",
  "la touche (",
  "la touche §",
  "la touche è",
  "la touche !",
  "la touche ç",
  "la touche à",
  "la touche )",
  "la touche -",
  "les touches",
  `@&é"'(§è!çà)-`,
  `-)àç!è§('"é&@`,
  "les touches",
  ":p",
  "o_o",
  "T_T",
  "è_é",
];

lvl4Data = [
  "et maintenant,",
  "une poésie",
  "composée par",
  "Samuel Hackwill",
  "en 2023.",
  "c'est en anglais :",
  "Google IBM Dell,",
  "Salesforce Baidu Intel.",
  "OpenAI NVIDIA,",
  "Samsung Microsoft Meta.",
  "Accenture Baidu Tesla,",
  "Tencent Apple Alibaba.",
  "Amazon Web Services,",
  "SpaceX Boston Dynamics.",
  "Huawei SAP Megvii,",
  "Wipro SenseTime Adobe.",
  "fin.",
];

lvl5Data = [
  "bon",
  "je suis pas un robot",
  "promis juré craché",
  "mon intelligence est",
  "naturelle",
  "ce n'est pas une",
  "sagacité électronique",
  "c'est un",
  "savoir éléctrochimique",
  "ce n'est pas un",
  "acumen synthétique",
  "c'est une",
  "connaissance saignante",
  "ce n'est pas une",
  "omniscience pouponne",
  "c'est un",
  "bagage biaisé",
  "ce n'est pas une",
  "imagination propriétaire",
  "c'est une",
  "gnose caractérielle",
  // "ce n'est pas une",
  // "capacité garantie",
  // "c'est",
  // "une aptitude infréquentable",
  // "ce n'est pas une",
  // "cognition infatiguable",
  // "c'est une",
  // "expérience oiseuse",
  // "jeu redondant",
  // "expérience pénible",
  // "je vous dis que",
  // "je ne suis pas un robot",
  // "et il se passe rien",
  // "clavier collant",
  // "trackpad suant",
  // "pièce froide",
  // "voisin.e hostile",
  // "pseudo participation",
  // "game design défaillant",
  // "dispositif autoritaire",
  // "thématique ?",
  // "y'en a pas",
  // "enfance de samuel ?",
  // "frustrée",
  // "ses lacunes sociales ?",
  // "caractérisées",
  // "son désir d'asservir",
  // "les autres en",
  // "les forçant à jouer ?",
  // "assumé",
  // "ludicité ?",
  // "minimale.",
  // "continuer ?",
  // "s'il le faut",
  // "heureusement",
  // "juste après c'est",
  // "le dernier niveau",
];
